version: '3.3'

services:            
    # https://hub.docker.com/r/plexinc/pms-docker/
    plex:
        container_name: plex
        image: plexinc/pms-docker:latest
        restart: unless-stopped
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        networks:
            - frontend
        environment:
            - TZ=America/Los_Angeles
            - PLEX_CLAIM=claim-pAqtwUxPYS8_uDzPhaqe
            - ADVERTISE_IP=http://192.168.86.11:32400/
        hostname: dionysus
        volumes:
            - /var/lib/plex:/config
            - /var/tmp/plex:/transcode
            - /srv/media:/data

    # https://github.com/NitriKx/docker-Plex-Cleaner
    plex-cleaner:
        image: nitrikx/plex-cleaner
        container_name: plex-cleaner
        environment:
            # Execute the script at 7pm on the first of every month
            - EXECUTION_CRON_EXPRESSION=0 19 1 * *
        volumes:
            - /var/lib/plex:/config
            - /srv/media:/plexdata
            # - ./logs:/logs

    # https://hub.docker.com/r/homeassistant/home-assistant
    # https://www.home-assistant.io/installation/linux
    # homeassistant:
    #     container_name: homeassistant
    #     image: homeassistant/home-assistant:stable
    #     restart: unless-stopped
    #     # networks:
    #     #     - frontend
    #     volumes:
    #         - /var/lib/homeassistant:/config
    #         - /etc/localtime:/etc/localtime:ro
    #     network_mode: host

    # https://hub.docker.com/r/oznu/homebridge
    homebridge:
        container_name: homebridge
        image: oznu/homebridge:latest
        restart: unless-stopped
        network_mode: host
        environment:
            - PGID=1000
            - PUID=1000
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_CONFIG_UI_PORT=8581
            - TZ=US/Pacific
        volumes:
            - /var/lib/homebridge:/homebridge

networks:
    frontend:
    #backend:
